# Generated by Django 5.2.4 on 2025-08-12 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paystackpayment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Paystack Payment', 'verbose_name_plural': 'Paystack Payments'},
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in Naira', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Full Paystack API response', null=True),
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='reference',
            field=models.CharField(help_text='Paystack reference for this payment', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
