# Generated by Django 5.2.4 on 2025-08-17 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paystackpayment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='initialized', max_length=16)),
                ('authorization_url', models.URLField(blank=True, null=True)),
                ('access_code', models.CharField(blank=True, max_length=64, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('init_response', models.JSONField(blank=True, null=True)),
                ('verify_response', models.JSONField(blank=True, null=True)),
                ('webhook_events', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='PaystackPayment',
        ),
    ]
