# Generated by Django 5.2.4 on 2025-08-08 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_providerlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerlog',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='providerlog',
            name='client_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='providerlog',
            name='status_code',
            field=models.CharField(default=200, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providerlog',
            name='service_type',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data')], max_length=10),
        ),
    ]
