# Generated by Django 5.2.4 on 2025-08-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_backfill_client_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimetransaction',
            name='client_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='client_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
