# Generated by Django 5.2.4 on 2025-08-12 21:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_airtimetransaction_client_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtimetransaction',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='datatransaction',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='providerlog',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='airtimetransaction',
            name='provider_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airtimetransaction',
            name='provider_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='airtimetransaction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datatransaction',
            name='provider_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatransaction',
            name='provider_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='datatransaction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='providerlog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='providerlog',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providerlog',
            name='provider',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='providerlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='providerlog',
            name='response_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airtimetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='airtimetransaction',
            name='client_reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='airtimetransaction',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='airtimetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='client_reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerlog',
            name='client_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='providerlog',
            name='service_type',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('vtpass', 'VTpass'), ('paystack', 'Paystack')], default='vtpass', max_length=10),
        ),
        migrations.AlterField(
            model_name='providerlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='airtimetransaction',
            index=models.Index(fields=['status', 'timestamp'], name='services_ai_status_2c1175_idx'),
        ),
        migrations.AddIndex(
            model_name='airtimetransaction',
            index=models.Index(fields=['network', 'timestamp'], name='services_ai_network_d80f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='datatransaction',
            index=models.Index(fields=['status', 'timestamp'], name='services_da_status_73bfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='datatransaction',
            index=models.Index(fields=['network', 'timestamp'], name='services_da_network_d21452_idx'),
        ),
        migrations.AddIndex(
            model_name='providerlog',
            index=models.Index(fields=['service_type', 'timestamp'], name='services_pr_service_849852_idx'),
        ),
        migrations.AddIndex(
            model_name='providerlog',
            index=models.Index(fields=['status_code', 'timestamp'], name='services_pr_status__41a4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='providerlog',
            index=models.Index(fields=['request_id'], name='services_pr_request_4a25ab_idx'),
        ),
    ]
