# Generated by Django 5.2.4 on 2025-08-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_airtimetransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimetransaction',
            name='provider_reference',
            field=models.CharField(blank=True, help_text='Provider transactionId or equivalent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airtimetransaction',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datatransaction',
            name='provider_reference',
            field=models.CharField(blank=True, help_text='Provider transactionId or equivalent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatransaction',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airtimetransaction',
            name='provider_request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Provider-side request/reference id (e.g., VTpass request_id)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airtimetransaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='provider_request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Provider-side request/reference id (e.g., VTpass request_id)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datatransaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
    ]
