# Generated by Django 5.2.4 on 2025-08-08 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=128)),
                ('txn_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data')], max_length=16)),
                ('txn_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='rewards_loy_user_id_67851f_idx'), models.Index(fields=['txn_type', 'txn_id'], name='rewards_loy_txn_typ_aade1a_idx')],
            },
        ),
    ]
